version: "3.9"

services:
  postgres-cooking-service:
    image: postgres:16
    container_name: postgres-cooking-service
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cooking-app
    ports:
      - "5438:5432"
    volumes:
      - postgres_cooking_data:/var/lib/postgresql/data
    networks:
      - compose_app_net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - compose_app_net

#  redis:
#    image: redis:7-alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - compose_app_net

#  redpanda:
#    image: redpandadata/redpanda:v25.2.6
#    container_name: redpanda
#    ports:
#      - "29092:29092"
#      - "19092:19092"
#      - "9644:9644"
#    command:
#      - redpanda
#      - start
#      - --overprovisioned
#      - --smp 1
#      - --memory 512M
#      - --reserve-memory 0M
#      - --node-id 0
#      - --check=false
#      - --kafka-addr INTERNAL://redpanda:19092,EXTERNAL://0.0.0.0:29092
#      - --advertise-kafka-addr INTERNAL://redpanda:19092,EXTERNAL://localhost:29092
#    volumes:
#      - redpanda_data:/var/lib/redpanda/data
#    networks:
#      - compose_app_net

networks:
  compose_app_net:
    driver: bridge

volumes:
  postgres_cooking_data:
  minio_data:
#  redpanda_data:
